<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class IndexText extends Model
{
    use HasFactory;

    protected $table = 'index_text';

    protected $fillable = [
        'about_title',
        'about_description',
        'about_img',
        'about_num_1',
        'about_description_1',
        'about_img_1',
        'about_num_2',
        'about_description_2',
        'about_img_2',
        'about_num_3',
        'about_description_3',
        'about_img_3',
        'service_title',
        'service_title_1',
        'service_description_1',
        'service_title_2',
        'service_description_2',
        'service_title_3',
        'service_description_3',
        'portifolio_title',
        'frame_num_1',
        'frame_legend_1',
        'frame_description_1',
        'frame_num_2',
        'frame_legend_2',
        'frame_description_2',
        'testimonials_title',
        'testimonials_description',
        'testimonials_num_1',
        'testimonials_description_1',
        'testimonials_img_1',
        'testimonials_company_1',
        'testimonials_name_1',
        'testimonials_num_2',
        'testimonials_description_2',
        'testimonials_img_2',
        'testimonials_company_2',
        'testimonials_name_2',
        'employee_title',
        'employee_name_1',
        'employee_work_1',
        'employee_img_1',
        'employee_url_facebook_1',
        'employee_url_instagram_1',
        'employee_url_twitter_1',
        'employee_name_2',
        'employee_work_2',
        'employee_img_2',
        'employee_url_facebook_2',
        'employee_url_instagram_2',
        'employee_url_twitter_2',
        'employee_name_3',
        'employee_work_3',
        'employee_img_3',
        'employee_url_facebook_3',
        'employee_url_instagram_3',
        'employee_url_twitter_3',
        'works_title',
        'works_title_1',
        'works_img_1',
        'works_date_1',
        'works_description_1',
        'works_title_2',
        'works_img_2',
        'works_date_2',
        'works_description_2',
        'works_title_3',
        'works_img_3',
        'works_date_3',
        'works_description_3',
        'final_title',
        'sign_title',
        'sign_description',
        'sign_rolling',
        'social_url_facebook',
        'social_url_instagram',
        'social_url_twitter',
        'contact_telephone',
        'contact_cellphone',
        'contact_email',
        'navigation_title_1',
        'navigation_url_1',
        'navigation_title_2',
        'navigation_url_2',
        'navigation_title_3',
        'navigation_url_3'
    ];

}
